development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: example
  pool: 5
  username: ali
  password: 12345678

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: example
  pool: 5
  username: ali
  password: 12345678